### ISSUE TITLE
결제모듈 방향 설정 

### ISSUE THREAD

**Issue by HYJ29** [heartright-co/expo-test-module#1]
- [x] 기존 pnuu 코드 분석 
- [x] import api 분석 
- [x] cloud funding 기능 구현하려면? ( 결제받고 -> 결제받은걸 돌려주려면 )

**Comment by byyoungjin** [comment]
## 기존 pnuu 코드 : 
### 기본로직 
https://www.npmjs.com/package/iamport-react-native 사용 (iam port 에서 지원하는 모듈)


### android 의 경우
희성님이 만든 php 웹 페이지로 param 넘겨서 routing 됨 -> 기존코드에서 얻을것 없음.
희성님 php 코드는 어디?

**Comment by byyoungjin** [comment]
## import api 분석 
### REST API 지원 
커스텀한 UI 가능?

**Comment by byyoungjin** [comment]
# Crowd funding 기능구현 가능성 체크 
## 1. Stripe : 지원하긴하지만 fit이 맞지않다. 
https://stripe.com/docs/connect/collect-then-transfer-guide?platform=web#testing
stripe 에 가입함으로써 payout 되게 만든다. 
cake 를 만드려면 stripe 에 가입해서 계좌를 만들고 연결해야한다. .. 직접 사용자들이.. 

### 한국유저들도 사용가능할까 
당연히 한국 bank 를 지원하지 않기때문에 안된다. 

### 결론 
기본적으로 한방향 결제만 지원한다.( customer -> stripe 유저 에게 결제 )

## 2. iamport : 마찬가지로 cloud funding 은 불가할듯 
(혹시몰라 mail 문의는 했음.) 
답변내용: stripe 와 마찬가지
![image](https://user-images.githubusercontent.com/44938459/114005258-56962c80-989a-11eb-8c8f-4bb438fdca4e.png)


## 3. 송금 api 
### 1. 카카오 :지원안함
단순 api 는 물론
 https://devtalk.kakao.com/t/api/109691/3
딥링크도.. 
https://devtalk.kakao.com/t/topic/110555


### 2.토스 :딥링크 지원함! 
단, 토스앱을 깔아야한다. 단순 api 가 아니라 deep 링크 스키마를통해 자연스럽게 '송금'할수 있도록 지원한다. 
입금버튼을 누르면 토스앱으로 바로 넘어가서 토스에서 해당 송금을 진행하는 내용. 
https://tossbutton.docs.apiary.io/#reference/0/0/api




## 결론 
전반적으로 결제 api는 ( stripe, import, 카카오, 토스) 양방향이 아니라 한방향이다. 유저끼리 송금 개념을 지원하진않는다. 

crowd 펀딩을 구현하려면 
1. [결제 api ] 유저가 stripe 등에 자신의 계정을 만들어서 crowd 펀딩을 모금을하고 입금을 받는다. 
-> 번거롭고, 현제 pnuu 모델은 crowd funding 이 빈번할 것으로 예상되서 적절하지 않다.

2.  송금서비스를 만든다..
-> 현재상황에서 불가능. (토스와 같은 기능을 만든다...) 

3. [결제 api ] 결제를 heartright 에서 일괄적으로 받고, 누구에게 얼마만큼 줘야하는지를 판단한다음에 
어떤 방법으로 각 개인에게 돈을 전달해준다. 
수작업으로한다면 각 개인의 개인 계좌에 입금해주는 방식등이 될 수있다.. 

3. [송금서비스 ]  기존의 송금서비스를 이용한다. ( 토스를 이용한다. ) 
flow: 
pnuu 앱내에서 금액과, 송금할 계좌정보와 함께 송금버튼을 누르면,
-> 사용자 휴대폰의 '토스앱' 이 실행되면서 송금정보가 전달된다. 
-> 토스 송금버튼을 누르면 토스앱 상에서 송금을 진행. 
-> pnuu 앱으로 돌아와서 확인절차가 필요하다. 몇가지 생각해보면 
 1번시나리오) 
 "보냈어요" "나중에 보내려구요" 이런 버튼을 넣어서 다음 flow 를 진행한다. 
 2번 시나리오 )
  토스앱으로 넘어가는 순간 무조건 보낸걸로 처리한다. 나중에 사용자가 정정할 수있도록 한다. 
 
-> 위와같은 방법으로 funding 금액, 송금한사람 등의 정보를 pnuu 앱상에서 보여준다. 
-> funding 마지막날 결과를 알려준다. ( 실제입금된 금액은 다를 수있다.) 


# 정리
#### 1. Crowd funding : 토스 송금서비스 이용하기 
3번 송금서비스로 crowdfunding 같은 서비스를 제공하는 방향이 좋은것 같다. 
1. 결제금액이 완전히 일치하느냐가 앱의 가치에 영향을 주는것이 아닌것같고 
2. toss 로 넘어가는 과정이 깔끔하고 사용자가 편하게 느낄수 있을것 같다.( 앱을 사용하고 있다면 ) 
3. 토스 입장에서도 이런 Deep 링크는 지속적으로 유지할것 같다. 
4. 무엇보다 사용자가 toss 앱을 이용하는것이기 때문에 결제 api 를 사용하는것과 달리 수수료가 들지않는다. 

#### 2. 구독관리:  Expo barework flow , 인앱결제 넣기 --> 나중에 안드로이드만 import 적용, 수수료 낮추기 
결제 api 로는 import 를 이용하면 될것 같지만,
ios 경우 subscription 에 다른 결제모듈을 사용하는것을 허락안함.
inapp 결제를 무조건 해야하는데( 30% 수수료 애플에 지불  ) 

expo 에서 지원하는 inapp 결제 module 은 bare-work flow 에서만 지원된다. 

기존 pnuu 앱은 managed 였는데, bare 로 하는게 configuration 은 많이 들어가지만 앱에대한 control 능력이 더 생기는거라 bare-work flow 로 진행하는것이 좋을듯함.

**Comment by insu-heartright** [comment]
### 의견
**크라우드펀딩(Crowd funding)**
1. 1/2/3 옵션 중에 딥링크를 지원하는 '토스'로 해보는 게 좋겠네요. 
2. 사용자의 수수료 부담도 없고, 2,000만의 가입자 중 페르소나에 가까운 유저(20대 초반 여성)들도 User Friendly하게 쓸 수 있을 거 같아요. 

**구독관리**
- control이 더 우위에 있는 bare-work flow로 우선 적용 후, 추후에 안드로이드에 import 적용하는 방향이 좋겠네요.
